name: Release

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID of the build workflow'
        required: true
        default: '13042045029'

jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Version
        id: extract
        run: |
          version=$(grep -oP 'const currentVersion = "\K[^"]+' downloader/main.go)
          echo "version=$version" >> "$GITHUB_OUTPUT"

  release:
    needs: extract_version
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ needs.extract_version.outputs.version }}
          name: Release ${{ needs.extract_version.outputs.version }}
          draft: true
          prerelease: false
          files: |
            patcher-epoch-linux-amd64
            patcher-epoch-windows-amd64.exe
            server-linux-amd64
            server-windows-amd64.exe
            LICENSE

